service: wozitech-lorien-tech-test

custom:
  environment: ${opt:stage, 'development'}
  bucketName: "${self:custom.environment}-thisbucket"
  region: ${opt:region, 'eu-west-1'}

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: ${self:custom.region}
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 5
  memorySize: 128
  environment:
    LOG_LEVEL: 1      # 0-disabled; 1-errors, 2-warnings, 3-info, 4-debug, 5-trace
  #role: arn:aws:iam::#{AWS::AccountId}:role/WOZiTech_eu_west_1_lambda_basic_role

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  organisation:
    handler: lorientechtest.handler
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    #role: arn:aws:iam::#{AWS::AccountId}:role/WOZiTech_eu_west_1_tfl_lambda_role    # note, the name of the role includes the region, but with underscores
    events:
      - http: POST organisation
      - http:
          path: organisation/{name}
          method: get
          request:
            parameters:
              path:
                name: true
      - http:
          path: organisation/{name}
          method: put
          request:
            parameters:
              path:
                name: true
    tags:
      company: "WOZiTech"
    package:
      include:
        - lorientechtest.js

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies